FROM maven:latest AS build
WORKDIR /app
COPY . .
RUN mvn clean install

FROM eclipse-temurin:latest
EXPOSE 8080
COPY --from=build /app/target/SorteioApi-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]